using Microsoft.SqlServer.Server;
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using System.Web;

namespace Gestor_IA.Classes
{
   

    public class Cadastro_de_Mercadorias
    {
        /// <summary>
        /// CAMPO DE CADASTRO DE MERCADORIAS
        /// </summary>
  

        private int codigoMercadoria;
        private string mercadoria;
        private string fabricante;
        private decimal precoC;
        private decimal precoVenda;
        private string fornecedor;
        private decimal unidadesEmEstoque;
        private DateTime dataEstoque;
        private string medida;
        private decimal icms;
        private decimal frete;
        private decimal ipi;
        private decimal precoCompra;
        private string prateleira;
        private string grupo;
        private string subGrupo;
        private decimal vendaA;
        private decimal vendaB;
        private decimal vendaC;
        private bool isentoICMS;
        private decimal maximo;
        private bool desativado;
        private decimal comissao2;
        private string codBarra;
        private string codFabricante;
        private decimal icms2;
        private decimal impFed;
        private string cf;
        private string d;
        private string o;
        private decimal impFisc;
        private decimal entradas;
        private decimal saidas;
        private decimal entMov;
        private decimal saiMov;
        private decimal entA;
        private decimal saiA;
        private decimal oEntA;
        private decimal oSaiA;
        private decimal unidadesEmEstoque2;
        private string emb;
        private decimal pis;
        private decimal cofins;
        private decimal iRenda;
        private decimal cSocial;
        private decimal despOperacionais;
        private decimal diversos;
        private decimal margemLucro;
        private decimal entradas2;
        private decimal saidas2;
        private decimal entMov2;
        private decimal precoNota;
        private DateTime ultimaEntrada;
        private decimal peso;
        private decimal financ;
        private decimal desco2;
        private decimal saidas3;
        private decimal precoVendaSugerido;
        private string chavePreco;
        private DateTime dataAlteracaoPreco;
        private string lancamentoUsuario;
        private DateTime lancamentoDataHora;
        private string observacao;
        private bool garantia;
        private bool devolucao;
        private bool requisicao;
        private bool cobrar10pc;
        private bool naoVender;
        private bool naoControlarEstoque;
        private string composicao;
        private bool viaCozinha;
        private bool possuiFoto;
        private string especificacoes;
        private string acompanhamento;
        private decimal promocaoPreco;
        private DateTime? promocaoValidade;
        private string classificacaoFiscal;
        private decimal restauranteDesconto;
        private bool restauranteAlterarPreco;
        private bool comunicadoAltPreco;
        private DateTime? dataDesativacao;
        private string tipoEspecifico;
        private string ncm;
        private string origem;
        private string lc;
        private string informacoesAdicionais;
        private string iat;
        private string ippt;
        private string spedTipoItem;
        private decimal smDescontoMaximo;
        private string smEspecificacao;
        private bool smNaoEnviarPalm;
        private decimal smQuantidadePromocao;
        private decimal smPromocaoPreco;
        private DateTime? smPromocaoValidade;
        private decimal smDescontoMaximoEx;
        private string xmlCodForne;
        private decimal quantEmbalagem;
        private string pafCodigo;
        private string pafDescricao;
        private decimal pafEstoque;
        private string pafAplicativo;
        private bool pafST;
        private decimal pafAliquota;
        private decimal pafValor;
        private bool solicitarSerial;
        private bool viaBar;
        private bool servicoConvenio115;
        private bool balanca;
        private int balancaValidadeDias;
        private decimal servicoPercConvenio115;
        private string codClassServico;
        private decimal quantidadeAcompanhamentos;
        private string url;
        private decimal quantEmbalagemVenda;
        private string barrasCaixa;
        private bool cartaoPresente;
        private bool promocaoMultiplos;
        private decimal promocaoQuantidadeBonificada;
        private bool vidroOptyWayExportar;
        private string vidroOptyWayCodigo;
        private string vidroOptyWayDescricao;
        private decimal vidroOptyWayEspessura;
        private string vidroOptyWayAresta;
        private string codigoSimilar;
        private string promocaoQuantidadeTipo;
        private string mercadoriaIngles;
        private bool converterEmKg;
        private bool naoCobrarTaxaServico;
        private decimal taxaEntrega;
        private string nve;
        private DateTime dataCadastro;
        private int validadeDias;
        private string cCest;
        private bool ncmSelecionar;
        private bool semDescontoConvenio;
        private bool naoBaixarComposicaoNaVenda;
        private bool restaurantePizza;
        private string restauranteTipoCalculo;
        private int idRestauranteSetor;
        private string promocaoTipo;
        private string ssCodigoProduto;
        private string ssCodigoProdutoUnicoGrade;
        private int familiaID;
        private decimal precoCompraAnterior;
        private bool vidroCorteCertoExportar;
        private string vidroCorteCertoCodigo;
        private string vidroCorteCertoDescricao;
        private string cProdANVISA;
        private string combCProdANP;
        private bool perguntarAdicional;
        private decimal estoqueReservado;
        private bool petShopPacote;
        private int petShopIDPacote;
        private string xMotivoIsencao;
        private bool eCommerceIrParaSite;
        private string eCommerceDescricaoParaSite;
        private decimal eCommerceFatorDeConversao;
        private bool sefiiIncentivoFiscal;
        private decimal sefiiIncentivoPercentual;
        private DateTime? sefiiIncentivoPrazoFruicao;
        private decimal vendaD;
        private decimal vendaE;
        private string infAdCodigo;
        private decimal combpGLP;
        private decimal combpGNn;
        private decimal combpGNi;
        private decimal combvPart;
        private string eCommerceCodigoSite;
        private decimal eCommerceAltura;
        private decimal eCommerceLargura;
        private decimal eCommerceComprimento;
        private decimal eCommerceEstoque;
        private string anvisaNomeTecnico;
        private DateTime? anvisaVigencia;
        private string anvisaClasseRisco;
        private decimal uberTaxaPedidoPequeno;
        private decimal embalagemTaxa;
        private bool marketplaceIntegrar;
        private string registroMS;
        private string classeTerapeutica;
        private bool usoProlongado;
        private string apresentacao;
        private string lista;
        private string substanciaCodDCB;
        private decimal dosagemMinima;
        private decimal dosagemMaxima;
        private decimal deliveryTaxaAdicional;
        private decimal dimensaoAltura;
        private decimal dimensaoLargura;
        private decimal dimensaoComprimento;
        private bool marketplaceIntegracaoPersonalizar;
        private string marketplaceURLsImagem;
        private string tipoCombo;
        private string tipoFaturamento;
        private decimal icmsAdRem;
        private decimal icmspRedAdRem;
        private string icmsMotRedAdRem;
        private decimal icmsAdRemICMSReten;
        private decimal icmsAdRemICMSRet;
        private decimal pBio;
        private bool agruparImpressaoItemCombo;
        private decimal precoAPartirDe;
        private string receitaTipo;
    }

}
